### ISSUE TITLE
Convertional Commits への対応

### ISSUE THREAD

**Issue by woodnx** [woodnx/iQbe#43]
### Overview
コミットメッセージの書式を統一する
Github Actionsなどを使用して自動でCHANGEROGやリリースノートを自動化したい

### 参考資料
- https://www.conventionalcommits.org/ja/v1.0.0-beta.4/
- https://www.npmjs.com/package/conventional-changelog-cli
- https://wp-kyoto.net/generate-changelog-by-conventional-changelog-cli/

**Comment by woodnext** [comment]
## 備忘録
### どのようにして，Branch -> Commit -> Pull Requestでのワークフローで自動的にCHANGE.LOGやRelease Notesを作成するのか
1. とりあえず，[Conventional Commits](https://www.conventionalcommits.org/ja/v1.0.0-beta.4/) / [Semantic Commit Messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716)に従う
2. これを使えば，[自動CHANGE.LOG生成ができるらしい](https://www.memory-lovers.blog/entry/2022/11/25/165938/)
3. [コミットメッセージの書式統一](https://makky12.hatenablog.com/entry/2022/01/17/120500)には，[git templateへの適用](https://qiita.com/takiguchi-yu/items/bef6074da3c71a863a67)や，[cz-cli](https://github.com/commitizen/cz-cli), [giz-cz](https://github.com/streamich/git-cz)がある

#### 備考
- Semantic Commit Messagesの詳細は[こちら](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716)

**Comment by woodnext** [comment]
## 流れ
1. 追加したい機能，バグ修正などごとにbranchを切る
2. 切ったブランチで適宜Conventional Commitsに従ったメッセージでcommitする
4. リモートにpushする
5. pushする際，細かいcommitは[squash](https://qiita.com/ke_sukesakuma/items/c94006f43cfc377e0e95)してまとめる
6. PRを作成し，レビューを受ける
7. PRをsquash-mergeでmainにマージ
8. PRのマージが行われたら，[設定したGitHubActions](https://zenn.dev/hamakou108/articles/ab6466afbcbaa9)が走り，リリース PR が作成される
9. リリースPRをマージすると，CHANGELOG，バージョン番号が更新され，リリースノートが作成される
