### ISSUE TITLE
OpenAPIへの対応とAPI Validationの追加

### ISSUE THREAD

**Issue by woodnx** [woodnx/iQbe#45]
routesに全部の実装を書くのをやめて，ModelとControllerに分割したい．
- Model: DBとの接続を担当，DBへのCRUDを抽象化する
- Controller: Modelで作った関数をもとにロジックを作成

https://swallow-incubate.com/archives/blog/20190425
https://qiita.com/a1k4r/items/82c62b7783837090ef27

**Comment by woodnext** [comment]
### やりたいこと
- [] 型セーフなRequestとResponce
  - [type-predicates-generator](https://github.com/d-kimuson/type-predicates-generator)を使って，NonOptinalなRequestQueryでNull値を得た場合は，400Errorを返すようにする
  - OpenAPI SchemaでAPI設計を記述し，index.jsから返すように変更
  - [aspida](https://github.com/aspida/aspida)と[openapi2aspida](https://github.com/aspida/openapi2aspida)を使って，型セーフなAPIリクエストを実現
  - Responce型もOpenAPI Schemaから生成された型を用いる
- [] RouteをControllerとで整理して共通部分の抽象化を行う

**Comment by woodnext** [comment]
04/06
### やることリスト
- トランザクション時の処理をちゃんとする

**Comment by woodnext** [comment]
# Clean Architectureの導入について
## Domain層
- そのシステムでやりたいことを基準にドメインを切る
  - やりたいことの例
    - ユーザ管理 → User Domain
    - 認証認可系 → Auth Domain
- 関心をまとめる
### Model
- そのdomainに対して、どんなデータが必要なのかを記述
### Service
- そのデータをどんなふうに処理するか
### Repository
- DBとの通信するメソッドをinterfaceとして記述
- 実装はInfra層で行う

## Infra層
- DBとの通信を担当する
- Domain層からInterfaceを受け取って、実装を行う
